@startuml activity-password-check-step
title Password Analyzer

start
:Input Password;
:Validasi Aturan Dasar;
if (Panjang & Variasi Karakter OK?) then (Yes)
    :Tambahkan Skor;
else (No)
    :Kurangi Skor;
endif

:Cek Pola Umum;
if (Pola Terlalu Mudah?) then (Yes)
    :Kurangi Skor;
else (No)
    :Tambahkan Skor;
endif

:Cek Database Lokal;
if (Ada di Dataset?) then (Yes)
    :Kurangi Skor Besar;
else (No)
    :Tidak Ada Aksi;
endif

:Cek API "Have I Been Pwned";
if (Password Pernah Bocor?) then (Yes)
    :Kurangi Skor Besar;
else (No)
    :Tidak Ada Aksi;
endif

:Analisis Statistik;
:Simulasi Serangan;
:Output Skor dan Rekomendasi;
stop


@enduml